apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-secret
  labels:
    tier: airflow
    component: airflow-db
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  postgres_db: cG9zdGdyZXM=
type: Opaque