apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    tier: airflow
    component: airflow-db
spec:
  selector:
    tier: airflow
    component: airflow-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432