apiVersion: v1
kind: Secret
metadata:
  name: "airflow-connections"
  labels:
    release: airflow
    chart: "airflow-1.2.0"
    heritage: Helm
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
data:
  AIRFLOW_CONN_AWS: 'YXdzOi8vQUtJQVRaSERXRFpQNkE0UlJPQTQ6WGxxUUp1YUdlMmJra0hSeTRnNVdKUkJBc00yTkV6UUJVeW5URnlYK0A='