kind: Secret
apiVersion: v1
metadata:
  name: airflow-metadata
  labels:
    tier: airflow
    release: airflow
    chart: airflow
    heritage: Helm
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=