kind: Secret
apiVersion: v1
metadata:
  name: airflow-redis-password
  labels:
    tier: airflow
    component: redis
    release: airflow
    chart: airflow
    heritage: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  password: "WkIzOVdMczNZZw=="

---

kind: Secret
apiVersion: v1
metadata:
  name: airflow-broker-url
  labels:
    tier: airflow
    component: redis
    release: airflow
    chart: airflow
    heritage: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  connection: "cmVkaXM6Ly86WkIzOVdMczNZZ0BhaXJmbG93LXJlZGlzOjYzNzkvMA=="
