kind: Secret
apiVersion: v1
metadata:
  name: airflow-result-backend
  labels:
    tier: airflow
    release: airflow
    chart: airflow
    heritage: Helm
type: Opaque
data:
  connection: "ZGIrcG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGFpcmZsb3ctcG9zdGdyZXNxbDo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZQ=="