kind: Secret
apiVersion: v1
metadata:
  name: airflow-webserver-secret-key
  labels:
    tier: airflow
    component: webserver
    release: airflow
    chart: airflow
    heritage: Helm
type: Opaque
data: 
  webserver-secret-key: "NDBmYzhkZjc2YzY2ZDk2M2VjNGI1OTFkMDQ5YjRjMjU="