kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-pod-log-reader-rolebinding
  labels:
    tier: airflow
    component: pod-log-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: airflow-webserver