apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KennedyUC/git-sync-test.git
    targetRevision: main
    path: airflow/overlays/stg
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-stg
  syncPolicy:
    automated:
      prune: true